C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyinitblock7(setupfunc)
      external setupfunc
      real d1
      real xkk
      real fp30
      real fp3u
      real fp1
      real fp2
      common /block7/ d1,xkk,fp30,fp3u,fp1,fp2
      call setupfunc(d1,xkk,fp30,fp3u,fp1,fp2)
      end

      subroutine f2pyinitblock6(setupfunc)
      external setupfunc
      real hmd
      real nmd
      real hdx
      common /block6/ hmd,nmd,hdx
      call setupfunc(hmd,nmd,hdx)
      end

      subroutine f2pyinitblock5(setupfunc)
      external setupfunc
      logical enight
      real e(4)
      common /block5/ enight,e
      call setupfunc(enight,e)
      end

      subroutine f2pyinitblock4(setupfunc)
      external setupfunc
      real hme
      real nme
      real hef
      common /block4/ hme,nme,hef
      call setupfunc(hme,nme,hef)
      end

      subroutine f2pyinitconst(setupfunc)
      external setupfunc
      real umr
      common /const/ umr
      call setupfunc(umr)
      end

      subroutine f2pyinitblock2(setupfunc)
      external setupfunc
      real b0
      real b1
      real c1
      common /block2/ b0,b1,c1
      call setupfunc(b0,b1,c1)
      end

      subroutine f2pyinitblock1(setupfunc)
      external setupfunc
      real hmf2
      real nmf2
      real hmf1
      logical f1reg
      common /block1/ hmf2,nmf2,hmf1,f1reg
      call setupfunc(hmf2,nmf2,hmf1,f1reg)
      end

      subroutine f2pyinitblock8(setupfunc)
      external setupfunc
      real hs
      real tnhs
      real xsm(4)
      real mm(5)
      real dti(4)
      integer mxsm
      common /block8/ hs,tnhs,xsm,mm,dti,mxsm
      call setupfunc(hs,tnhs,xsm,mm,dti,mxsm)
      end

      subroutine f2pyinitargexp(setupfunc)
      external setupfunc
      real argmax
      common /argexp/ argmax
      call setupfunc(argmax)
      end

      subroutine f2pyinitiounit(setupfunc)
      external setupfunc
      integer konsol
      common /iounit/ konsol
      call setupfunc(konsol)
      end

      subroutine f2pyinitblo11(setupfunc)
      external setupfunc
      real b2top
      real tc3
      integer itopn
      real alg10
      real hcor1
      common /blo11/ b2top,tc3,itopn,alg10,hcor1
      call setupfunc(b2top,tc3,itopn,alg10,hcor1)
      end

      subroutine f2pyinitblo10(setupfunc)
      external setupfunc
      real beta
      real eta
      real delta
      real zeta
      common /blo10/ beta,eta,delta,zeta
      call setupfunc(beta,eta,delta,zeta)
      end

      subroutine f2pyinitconst1(setupfunc)
      external setupfunc
      real humr
      real dumr
      common /const1/ humr,dumr
      call setupfunc(humr,dumr)
      end

      subroutine f2pyinitblote(setupfunc)
      external setupfunc
      real ahh(7)
      real ate1
      real stte(6)
      real dte(5)
      common /blote/ ahh,ate1,stte,dte
      call setupfunc(ahh,ate1,stte,dte)
      end

      subroutine f2pyinitconst2(setupfunc)
      external setupfunc
      integer icalls
      integer nmono
      integer iyearo
      integer idaynro
      logical rzino
      logical igino
      real ut0
      common /const2/ icalls,nmono,iyearo,idaynro,rzino,igino,ut0
      call setupfunc(icalls,nmono,iyearo,idaynro,rzino,igino,ut0)
      end

      subroutine f2pyinitblock3(setupfunc)
      external setupfunc
      real hz
      real t
      real hst
      common /block3/ hz,t,hst
      call setupfunc(hz,t,hst)
      end

      subroutine f2pyinitqtop(setupfunc)
      external setupfunc
      real y05
      real h05top
      real qf
      real xnetop
      real xm3000
      real hhalf
      real tau
      common /qtop/ y05,h05top,qf,xnetop,xm3000,hhalf,tau
      call setupfunc(y05,h05top,qf,xnetop,xm3000,hhalf,tau)
      end

      subroutine f2pyinitfindrlat(setupfunc)
      external setupfunc
      real flon
      real ryear
      common /findrlat/ flon,ryear
      call setupfunc(flon,ryear)
      end


