/* File: hwm07module.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Mon Jul 20 13:08:55 2015
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *hwm07_error;
static PyObject *hwm07_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = hwm07_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = hwm07_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
  double d=0.0;
  if (double_from_pyobj(&d,obj,errmess)) {
    *v = (float)d;
    return 1;
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(hwm07,HWM07)(int*,float*,float*,float*,float*,float*,float*,float*,float*,float*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** hwm07 ***********************************/
static char doc_f2py_rout_hwm07_hwm07[] = "\
Function signature:\n\
  w = hwm07(iyd,sec,alt,glat,glon,stl,f107a,f107,ap)\n\
Required arguments:\n"
"  iyd : input int\n"
"  sec : input float\n"
"  alt : input float\n"
"  glat : input float\n"
"  glon : input float\n"
"  stl : input float\n"
"  f107a : input float\n"
"  f107 : input float\n"
"  ap : input rank-1 array('f') with bounds (2)\n"
"Return objects:\n"
"  w : rank-1 array('f') with bounds (2)";
/* extern void F_FUNC(hwm07,HWM07)(int*,float*,float*,float*,float*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_hwm07_hwm07(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int iyd = 0;
  PyObject *iyd_capi = Py_None;
  float sec = 0;
  PyObject *sec_capi = Py_None;
  float alt = 0;
  PyObject *alt_capi = Py_None;
  float glat = 0;
  PyObject *glat_capi = Py_None;
  float glon = 0;
  PyObject *glon_capi = Py_None;
  float stl = 0;
  PyObject *stl_capi = Py_None;
  float f107a = 0;
  PyObject *f107a_capi = Py_None;
  float f107 = 0;
  PyObject *f107_capi = Py_None;
  float *ap = NULL;
  npy_intp ap_Dims[1] = {-1};
  const int ap_Rank = 1;
  PyArrayObject *capi_ap_tmp = NULL;
  int capi_ap_intent = 0;
  PyObject *ap_capi = Py_None;
  float *w = NULL;
  npy_intp w_Dims[1] = {-1};
  const int w_Rank = 1;
  PyArrayObject *capi_w_tmp = NULL;
  int capi_w_intent = 0;
  static char *capi_kwlist[] = {"iyd","sec","alt","glat","glon","stl","f107a","f107","ap",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOO:hwm07.hwm07",\
    capi_kwlist,&iyd_capi,&sec_capi,&alt_capi,&glat_capi,&glon_capi,&stl_capi,&f107a_capi,&f107_capi,&ap_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable iyd */
    f2py_success = int_from_pyobj(&iyd,iyd_capi,"hwm07.hwm07() 1st argument (iyd) can't be converted to int");
  if (f2py_success) {
  /* Processing variable glon */
    f2py_success = float_from_pyobj(&glon,glon_capi,"hwm07.hwm07() 5th argument (glon) can't be converted to float");
  if (f2py_success) {
  /* Processing variable stl */
    f2py_success = float_from_pyobj(&stl,stl_capi,"hwm07.hwm07() 6th argument (stl) can't be converted to float");
  if (f2py_success) {
  /* Processing variable glat */
    f2py_success = float_from_pyobj(&glat,glat_capi,"hwm07.hwm07() 4th argument (glat) can't be converted to float");
  if (f2py_success) {
  /* Processing variable f107a */
    f2py_success = float_from_pyobj(&f107a,f107a_capi,"hwm07.hwm07() 7th argument (f107a) can't be converted to float");
  if (f2py_success) {
  /* Processing variable ap */
  ap_Dims[0]=2;
  capi_ap_intent |= F2PY_INTENT_IN;
  capi_ap_tmp = array_from_pyobj(PyArray_FLOAT,ap_Dims,ap_Rank,capi_ap_intent,ap_capi);
  if (capi_ap_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(hwm07_error,"failed in converting 9th argument `ap' of hwm07.hwm07 to C/Fortran array" );
  } else {
    ap = (float *)(capi_ap_tmp->data);

  /* Processing variable sec */
    f2py_success = float_from_pyobj(&sec,sec_capi,"hwm07.hwm07() 2nd argument (sec) can't be converted to float");
  if (f2py_success) {
  /* Processing variable w */
  w_Dims[0]=2;
  capi_w_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_w_tmp = array_from_pyobj(PyArray_FLOAT,w_Dims,w_Rank,capi_w_intent,Py_None);
  if (capi_w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(hwm07_error,"failed in converting hidden `w' of hwm07.hwm07 to C/Fortran array" );
  } else {
    w = (float *)(capi_w_tmp->data);

  /* Processing variable f107 */
    f2py_success = float_from_pyobj(&f107,f107_capi,"hwm07.hwm07() 8th argument (f107) can't be converted to float");
  if (f2py_success) {
  /* Processing variable alt */
    f2py_success = float_from_pyobj(&alt,alt_capi,"hwm07.hwm07() 3rd argument (alt) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&iyd,&sec,&alt,&glat,&glon,&stl,&f107a,&f107,ap,w);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_w_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of alt*/
  /* End of cleaning variable alt */
  } /*if (f2py_success) of f107*/
  /* End of cleaning variable f107 */
  }  /*if (capi_w_tmp == NULL) ... else of w*/
  /* End of cleaning variable w */
  } /*if (f2py_success) of sec*/
  /* End of cleaning variable sec */
  if((PyObject *)capi_ap_tmp!=ap_capi) {
    Py_XDECREF(capi_ap_tmp); }
  }  /*if (capi_ap_tmp == NULL) ... else of ap*/
  /* End of cleaning variable ap */
  } /*if (f2py_success) of f107a*/
  /* End of cleaning variable f107a */
  } /*if (f2py_success) of glat*/
  /* End of cleaning variable glat */
  } /*if (f2py_success) of stl*/
  /* End of cleaning variable stl */
  } /*if (f2py_success) of glon*/
  /* End of cleaning variable glon */
  } /*if (f2py_success) of iyd*/
  /* End of cleaning variable iyd */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of hwm07 ********************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"hwm07",-1,{{-1}},0,(char *)F_FUNC(hwm07,HWM07),(f2py_init_func)f2py_rout_hwm07_hwm07,doc_f2py_rout_hwm07_hwm07},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "hwm07",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyObject *PyInit_hwm07(void) {
#else
#define RETVAL
PyMODINIT_FUNC inithwm07(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = hwm07_module = PyModule_Create(&moduledef);
#else
  m = hwm07_module = Py_InitModule("hwm07", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module hwm07 (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'hwm07' is auto-generated with f2py (version:2).\nFunctions:\n"
"  w = hwm07(iyd,sec,alt,glat,glon,stl,f107a,f107,ap)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  hwm07_error = PyErr_NewException ("hwm07.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"hwm07");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
