/* File: igrfmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Mon Jul 20 13:08:55 2015
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *igrf_error;
static PyObject *igrf_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = igrf_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = igrf_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
  double d=0.0;
  if (double_from_pyobj(&d,obj,errmess)) {
    *v = (float)d;
    return 1;
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(igrf11,IGRF11)(int*,float*,double*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*);
extern void F_FUNC(dmddec,DMDDEC)(int*,int*,double*);
extern void F_FUNC(ddecdm,DDECDM)(double*,int*,int*);
extern void F_FUNC(igrf11syn,IGRF11SYN)(int*,float*,int*,double*,double*,double*,double*,double*,double*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** igrf11 ***********************************/
static char doc_f2py_rout_igrf_igrf11[] = "\
Function signature:\n\
  alat,alon,ad,as,ah,ax,ay,az,af = igrf11(itype,date,alt,ifl,xlti,xltf,xltd,xlni,xlnf,xlnd)\n\
Required arguments:\n"
"  itype : input int\n"
"  date : input float\n"
"  alt : input float\n"
"  ifl : input int\n"
"  xlti : input float\n"
"  xltf : input float\n"
"  xltd : input float\n"
"  xlni : input float\n"
"  xlnf : input float\n"
"  xlnd : input float\n"
"Return objects:\n"
"  alat : rank-1 array('d') with bounds (totpts)\n"
"  alon : rank-1 array('d') with bounds (totpts)\n"
"  ad : rank-1 array('d') with bounds (totpts)\n"
"  as : rank-1 array('d') with bounds (totpts)\n"
"  ah : rank-1 array('d') with bounds (totpts)\n"
"  ax : rank-1 array('d') with bounds (totpts)\n"
"  ay : rank-1 array('d') with bounds (totpts)\n"
"  az : rank-1 array('d') with bounds (totpts)\n"
"  af : rank-1 array('d') with bounds (totpts)";
/* extern void F_FUNC(igrf11,IGRF11)(int*,float*,double*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*); */
static PyObject *f2py_rout_igrf_igrf11(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,double*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int itype = 0;
  PyObject *itype_capi = Py_None;
  float date = 0;
  PyObject *date_capi = Py_None;
  double alt = 0;
  PyObject *alt_capi = Py_None;
  int ifl = 0;
  PyObject *ifl_capi = Py_None;
  double xlti = 0;
  PyObject *xlti_capi = Py_None;
  double xltf = 0;
  PyObject *xltf_capi = Py_None;
  double xltd = 0;
  PyObject *xltd_capi = Py_None;
  double xlni = 0;
  PyObject *xlni_capi = Py_None;
  double xlnf = 0;
  PyObject *xlnf_capi = Py_None;
  double xlnd = 0;
  PyObject *xlnd_capi = Py_None;
  double *alat = NULL;
  npy_intp alat_Dims[1] = {-1};
  const int alat_Rank = 1;
  PyArrayObject *capi_alat_tmp = NULL;
  int capi_alat_intent = 0;
  double *alon = NULL;
  npy_intp alon_Dims[1] = {-1};
  const int alon_Rank = 1;
  PyArrayObject *capi_alon_tmp = NULL;
  int capi_alon_intent = 0;
  double *ad = NULL;
  npy_intp ad_Dims[1] = {-1};
  const int ad_Rank = 1;
  PyArrayObject *capi_ad_tmp = NULL;
  int capi_ad_intent = 0;
  double *as = NULL;
  npy_intp as_Dims[1] = {-1};
  const int as_Rank = 1;
  PyArrayObject *capi_as_tmp = NULL;
  int capi_as_intent = 0;
  double *ah = NULL;
  npy_intp ah_Dims[1] = {-1};
  const int ah_Rank = 1;
  PyArrayObject *capi_ah_tmp = NULL;
  int capi_ah_intent = 0;
  double *ax = NULL;
  npy_intp ax_Dims[1] = {-1};
  const int ax_Rank = 1;
  PyArrayObject *capi_ax_tmp = NULL;
  int capi_ax_intent = 0;
  double *ay = NULL;
  npy_intp ay_Dims[1] = {-1};
  const int ay_Rank = 1;
  PyArrayObject *capi_ay_tmp = NULL;
  int capi_ay_intent = 0;
  double *az = NULL;
  npy_intp az_Dims[1] = {-1};
  const int az_Rank = 1;
  PyArrayObject *capi_az_tmp = NULL;
  int capi_az_intent = 0;
  double *af = NULL;
  npy_intp af_Dims[1] = {-1};
  const int af_Rank = 1;
  PyArrayObject *capi_af_tmp = NULL;
  int capi_af_intent = 0;
  int totpts = 0;
  static char *capi_kwlist[] = {"itype","date","alt","ifl","xlti","xltf","xltd","xlni","xlnf","xlnd",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOO:igrf.igrf11",\
    capi_kwlist,&itype_capi,&date_capi,&alt_capi,&ifl_capi,&xlti_capi,&xltf_capi,&xltd_capi,&xlni_capi,&xlnf_capi,&xlnd_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable itype */
    f2py_success = int_from_pyobj(&itype,itype_capi,"igrf.igrf11() 1st argument (itype) can't be converted to int");
  if (f2py_success) {
  /* Processing variable xlti */
    f2py_success = double_from_pyobj(&xlti,xlti_capi,"igrf.igrf11() 5th argument (xlti) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xlnd */
    f2py_success = double_from_pyobj(&xlnd,xlnd_capi,"igrf.igrf11() 10th argument (xlnd) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xltd */
    f2py_success = double_from_pyobj(&xltd,xltd_capi,"igrf.igrf11() 7th argument (xltd) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xltf */
    f2py_success = double_from_pyobj(&xltf,xltf_capi,"igrf.igrf11() 6th argument (xltf) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xlni */
    f2py_success = double_from_pyobj(&xlni,xlni_capi,"igrf.igrf11() 8th argument (xlni) can't be converted to double");
  if (f2py_success) {
  /* Processing variable date */
    f2py_success = float_from_pyobj(&date,date_capi,"igrf.igrf11() 2nd argument (date) can't be converted to float");
  if (f2py_success) {
  /* Processing variable alt */
    f2py_success = double_from_pyobj(&alt,alt_capi,"igrf.igrf11() 3rd argument (alt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xlnf */
    f2py_success = double_from_pyobj(&xlnf,xlnf_capi,"igrf.igrf11() 9th argument (xlnf) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ifl */
    f2py_success = int_from_pyobj(&ifl,ifl_capi,"igrf.igrf11() 4th argument (ifl) can't be converted to int");
  if (f2py_success) {
  /* Processing variable totpts */
  totpts = (abs(xltf-xlti)/xltd+1)*(abs(xlnf-xlni)/xlnd+1);
  /* Processing variable alon */
  alon_Dims[0]=totpts;
  capi_alon_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_alon_tmp = array_from_pyobj(PyArray_DOUBLE,alon_Dims,alon_Rank,capi_alon_intent,Py_None);
  if (capi_alon_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(igrf_error,"failed in converting hidden `alon' of igrf.igrf11 to C/Fortran array" );
  } else {
    alon = (double *)(capi_alon_tmp->data);

  /* Processing variable af */
  af_Dims[0]=totpts;
  capi_af_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_af_tmp = array_from_pyobj(PyArray_DOUBLE,af_Dims,af_Rank,capi_af_intent,Py_None);
  if (capi_af_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(igrf_error,"failed in converting hidden `af' of igrf.igrf11 to C/Fortran array" );
  } else {
    af = (double *)(capi_af_tmp->data);

  /* Processing variable ah */
  ah_Dims[0]=totpts;
  capi_ah_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_ah_tmp = array_from_pyobj(PyArray_DOUBLE,ah_Dims,ah_Rank,capi_ah_intent,Py_None);
  if (capi_ah_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(igrf_error,"failed in converting hidden `ah' of igrf.igrf11 to C/Fortran array" );
  } else {
    ah = (double *)(capi_ah_tmp->data);

  /* Processing variable ay */
  ay_Dims[0]=totpts;
  capi_ay_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_ay_tmp = array_from_pyobj(PyArray_DOUBLE,ay_Dims,ay_Rank,capi_ay_intent,Py_None);
  if (capi_ay_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(igrf_error,"failed in converting hidden `ay' of igrf.igrf11 to C/Fortran array" );
  } else {
    ay = (double *)(capi_ay_tmp->data);

  /* Processing variable as */
  as_Dims[0]=totpts;
  capi_as_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_as_tmp = array_from_pyobj(PyArray_DOUBLE,as_Dims,as_Rank,capi_as_intent,Py_None);
  if (capi_as_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(igrf_error,"failed in converting hidden `as' of igrf.igrf11 to C/Fortran array" );
  } else {
    as = (double *)(capi_as_tmp->data);

  /* Processing variable alat */
  alat_Dims[0]=totpts;
  capi_alat_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_alat_tmp = array_from_pyobj(PyArray_DOUBLE,alat_Dims,alat_Rank,capi_alat_intent,Py_None);
  if (capi_alat_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(igrf_error,"failed in converting hidden `alat' of igrf.igrf11 to C/Fortran array" );
  } else {
    alat = (double *)(capi_alat_tmp->data);

  /* Processing variable ax */
  ax_Dims[0]=totpts;
  capi_ax_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_ax_tmp = array_from_pyobj(PyArray_DOUBLE,ax_Dims,ax_Rank,capi_ax_intent,Py_None);
  if (capi_ax_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(igrf_error,"failed in converting hidden `ax' of igrf.igrf11 to C/Fortran array" );
  } else {
    ax = (double *)(capi_ax_tmp->data);

  /* Processing variable az */
  az_Dims[0]=totpts;
  capi_az_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_az_tmp = array_from_pyobj(PyArray_DOUBLE,az_Dims,az_Rank,capi_az_intent,Py_None);
  if (capi_az_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(igrf_error,"failed in converting hidden `az' of igrf.igrf11 to C/Fortran array" );
  } else {
    az = (double *)(capi_az_tmp->data);

  /* Processing variable ad */
  ad_Dims[0]=totpts;
  capi_ad_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_ad_tmp = array_from_pyobj(PyArray_DOUBLE,ad_Dims,ad_Rank,capi_ad_intent,Py_None);
  if (capi_ad_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(igrf_error,"failed in converting hidden `ad' of igrf.igrf11 to C/Fortran array" );
  } else {
    ad = (double *)(capi_ad_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&itype,&date,&alt,&ifl,&xlti,&xltf,&xltd,&xlni,&xlnf,&xlnd,alat,alon,ad,as,ah,ax,ay,az,af,&totpts);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNNNNNNNN",capi_alat_tmp,capi_alon_tmp,capi_ad_tmp,capi_as_tmp,capi_ah_tmp,capi_ax_tmp,capi_ay_tmp,capi_az_tmp,capi_af_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_ad_tmp == NULL) ... else of ad*/
  /* End of cleaning variable ad */
  }  /*if (capi_az_tmp == NULL) ... else of az*/
  /* End of cleaning variable az */
  }  /*if (capi_ax_tmp == NULL) ... else of ax*/
  /* End of cleaning variable ax */
  }  /*if (capi_alat_tmp == NULL) ... else of alat*/
  /* End of cleaning variable alat */
  }  /*if (capi_as_tmp == NULL) ... else of as*/
  /* End of cleaning variable as */
  }  /*if (capi_ay_tmp == NULL) ... else of ay*/
  /* End of cleaning variable ay */
  }  /*if (capi_ah_tmp == NULL) ... else of ah*/
  /* End of cleaning variable ah */
  }  /*if (capi_af_tmp == NULL) ... else of af*/
  /* End of cleaning variable af */
  }  /*if (capi_alon_tmp == NULL) ... else of alon*/
  /* End of cleaning variable alon */
  /* End of cleaning variable totpts */
  } /*if (f2py_success) of ifl*/
  /* End of cleaning variable ifl */
  } /*if (f2py_success) of xlnf*/
  /* End of cleaning variable xlnf */
  } /*if (f2py_success) of alt*/
  /* End of cleaning variable alt */
  } /*if (f2py_success) of date*/
  /* End of cleaning variable date */
  } /*if (f2py_success) of xlni*/
  /* End of cleaning variable xlni */
  } /*if (f2py_success) of xltf*/
  /* End of cleaning variable xltf */
  } /*if (f2py_success) of xltd*/
  /* End of cleaning variable xltd */
  } /*if (f2py_success) of xlnd*/
  /* End of cleaning variable xlnd */
  } /*if (f2py_success) of xlti*/
  /* End of cleaning variable xlti */
  } /*if (f2py_success) of itype*/
  /* End of cleaning variable itype */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of igrf11 *******************************/

/*********************************** dmddec ***********************************/
static char doc_f2py_rout_igrf_dmddec[] = "\
Function signature:\n\
  x = dmddec(i,m)\n\
Required arguments:\n"
"  i : input int\n"
"  m : input int\n"
"Return objects:\n"
"  x : float";
/* extern void F_FUNC(dmddec,DMDDEC)(int*,int*,double*); */
static PyObject *f2py_rout_igrf_dmddec(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int i = 0;
  PyObject *i_capi = Py_None;
  int m = 0;
  PyObject *m_capi = Py_None;
  double x = 0;
  static char *capi_kwlist[] = {"i","m",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:igrf.dmddec",\
    capi_kwlist,&i_capi,&m_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable i */
    f2py_success = int_from_pyobj(&i,i_capi,"igrf.dmddec() 1st argument (i) can't be converted to int");
  if (f2py_success) {
  /* Processing variable x */
  /* Processing variable m */
    f2py_success = int_from_pyobj(&m,m_capi,"igrf.dmddec() 2nd argument (m) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&i,&m,&x);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",x);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of m*/
  /* End of cleaning variable m */
  /* End of cleaning variable x */
  } /*if (f2py_success) of i*/
  /* End of cleaning variable i */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of dmddec *******************************/

/*********************************** ddecdm ***********************************/
static char doc_f2py_rout_igrf_ddecdm[] = "\
Function signature:\n\
  i,m = ddecdm(x)\n\
Required arguments:\n"
"  x : input float\n"
"Return objects:\n"
"  i : int\n"
"  m : int";
/* extern void F_FUNC(ddecdm,DDECDM)(double*,int*,int*); */
static PyObject *f2py_rout_igrf_ddecdm(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double x = 0;
  PyObject *x_capi = Py_None;
  int i = 0;
  int m = 0;
  static char *capi_kwlist[] = {"x",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:igrf.ddecdm",\
    capi_kwlist,&x_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable i */
  /* Processing variable x */
    f2py_success = double_from_pyobj(&x,x_capi,"igrf.ddecdm() 1st argument (x) can't be converted to double");
  if (f2py_success) {
  /* Processing variable m */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&x,&i,&m);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("ii",i,m);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable m */
  } /*if (f2py_success) of x*/
  /* End of cleaning variable x */
  /* End of cleaning variable i */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of ddecdm *******************************/

/********************************* igrf11syn *********************************/
static char doc_f2py_rout_igrf_igrf11syn[] = "\
Function signature:\n\
  x,y,z,f = igrf11syn(isv,date,itype,alt,colat,elong)\n\
Required arguments:\n"
"  isv : input int\n"
"  date : input float\n"
"  itype : input int\n"
"  alt : input float\n"
"  colat : input float\n"
"  elong : input float\n"
"Return objects:\n"
"  x : float\n"
"  y : float\n"
"  z : float\n"
"  f : float";
/* extern void F_FUNC(igrf11syn,IGRF11SYN)(int*,float*,int*,double*,double*,double*,double*,double*,double*,double*); */
static PyObject *f2py_rout_igrf_igrf11syn(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,int*,double*,double*,double*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int isv = 0;
  PyObject *isv_capi = Py_None;
  float date = 0;
  PyObject *date_capi = Py_None;
  int itype = 0;
  PyObject *itype_capi = Py_None;
  double alt = 0;
  PyObject *alt_capi = Py_None;
  double colat = 0;
  PyObject *colat_capi = Py_None;
  double elong = 0;
  PyObject *elong_capi = Py_None;
  double x = 0;
  double y = 0;
  double z = 0;
  double f = 0;
  static char *capi_kwlist[] = {"isv","date","itype","alt","colat","elong",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO:igrf.igrf11syn",\
    capi_kwlist,&isv_capi,&date_capi,&itype_capi,&alt_capi,&colat_capi,&elong_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable colat */
    f2py_success = double_from_pyobj(&colat,colat_capi,"igrf.igrf11syn() 5th argument (colat) can't be converted to double");
  if (f2py_success) {
  /* Processing variable itype */
    f2py_success = int_from_pyobj(&itype,itype_capi,"igrf.igrf11syn() 3rd argument (itype) can't be converted to int");
  if (f2py_success) {
  /* Processing variable f */
  /* Processing variable isv */
    f2py_success = int_from_pyobj(&isv,isv_capi,"igrf.igrf11syn() 1st argument (isv) can't be converted to int");
  if (f2py_success) {
  /* Processing variable date */
    f2py_success = float_from_pyobj(&date,date_capi,"igrf.igrf11syn() 2nd argument (date) can't be converted to float");
  if (f2py_success) {
  /* Processing variable elong */
    f2py_success = double_from_pyobj(&elong,elong_capi,"igrf.igrf11syn() 6th argument (elong) can't be converted to double");
  if (f2py_success) {
  /* Processing variable y */
  /* Processing variable x */
  /* Processing variable alt */
    f2py_success = double_from_pyobj(&alt,alt_capi,"igrf.igrf11syn() 4th argument (alt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable z */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&isv,&date,&itype,&alt,&colat,&elong,&x,&y,&z,&f);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("dddd",x,y,z,f);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable z */
  } /*if (f2py_success) of alt*/
  /* End of cleaning variable alt */
  /* End of cleaning variable x */
  /* End of cleaning variable y */
  } /*if (f2py_success) of elong*/
  /* End of cleaning variable elong */
  } /*if (f2py_success) of date*/
  /* End of cleaning variable date */
  } /*if (f2py_success) of isv*/
  /* End of cleaning variable isv */
  /* End of cleaning variable f */
  } /*if (f2py_success) of itype*/
  /* End of cleaning variable itype */
  } /*if (f2py_success) of colat*/
  /* End of cleaning variable colat */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of igrf11syn ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"igrf11",-1,{{-1}},0,(char *)F_FUNC(igrf11,IGRF11),(f2py_init_func)f2py_rout_igrf_igrf11,doc_f2py_rout_igrf_igrf11},
  {"dmddec",-1,{{-1}},0,(char *)F_FUNC(dmddec,DMDDEC),(f2py_init_func)f2py_rout_igrf_dmddec,doc_f2py_rout_igrf_dmddec},
  {"ddecdm",-1,{{-1}},0,(char *)F_FUNC(ddecdm,DDECDM),(f2py_init_func)f2py_rout_igrf_ddecdm,doc_f2py_rout_igrf_ddecdm},
  {"igrf11syn",-1,{{-1}},0,(char *)F_FUNC(igrf11syn,IGRF11SYN),(f2py_init_func)f2py_rout_igrf_igrf11syn,doc_f2py_rout_igrf_igrf11syn},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "igrf",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyObject *PyInit_igrf(void) {
#else
#define RETVAL
PyMODINIT_FUNC initigrf(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = igrf_module = PyModule_Create(&moduledef);
#else
  m = igrf_module = Py_InitModule("igrf", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module igrf (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'igrf' is auto-generated with f2py (version:2).\nFunctions:\n"
"  alat,alon,ad,as,ah,ax,ay,az,af = igrf11(itype,date,alt,ifl,xlti,xltf,xltd,xlni,xlnf,xlnd)\n"
"  x = dmddec(i,m)\n"
"  i,m = ddecdm(x)\n"
"  x,y,z,f = igrf11syn(isv,date,itype,alt,colat,elong)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  igrf_error = PyErr_NewException ("igrf.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));




/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"igrf");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
